name: Validacion de Codigo Python

# El trigger: Esto indica que el pipeline se ejecutará con cada "push"
on: [push]

jobs:
  revision-linter:
    # El entorno donde se ejecutará el pipeline
    runs-on: ubuntu-latest

    steps:
      - name: 1. Obtener el código del repositorio
        uses: actions/checkout@v3

      - name: 2. Configurar el entorno de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 3. Instalar la herramienta Linter (Flake8)
        run: pip install flake8

      - name: 4. Ejecutar el análisis de código
        # Esta línea revisará app.py en busca de malas prácticas
        run: flake8 prueba.py
